command:
  - "python"
  - "app/main.py"

env:
  - name: sarvam_api_key
    valueFrom: "asha-sahayak.sarvam_api_key"
  - name: hf_api_key
    valueFrom: "asha-sahayak.hf_api_key"
  - name: ASHA_DELTA_BASE
    value: "/dbfs/asha_sahayak/delta"
  - name: ASHA_FAISS_PATH
    value: "/dbfs/asha_sahayak/faiss"
